version: '2'
services:
  ftp_server:
    image: 'dockersecplayground/alpine_ftp:v1.0'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.4
    cap_add:
      - ALL
  Alice:
    image: 'nsunina/alpine_netcat:v1.1'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.2
  Bob:
    image: 'nsunina/alpine_netcat:v1.1'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.3
  http_server:
    image: 'dockersecplayground/linode_lamp:v2.0'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.5
    volumes:
      - './website:/var/www/'
networks:
  mySubnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
