version: '2'
services:
  SMPT_server:
    image: 'nsunina/postfix:v1.1'
    stdin_open: true
    tty: true
    networks:
      public_network:
        ipv4_address: 193.21.1.3
networks:
  public_network:
    ipam:
      config:
        - subnet: 193.21.1.1/24
